source 'https://rubygems.org'
ruby '2.0.0'

gem 'rails', '4.0.0'
gem 'pg'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
gem 'haml-rails'
gem 'haml'
gem 'simple_form'
gem 'faker'
gem 'bootstrap-sass-rails'
gem 'devise'
gem 'quiet_assets'
gem 'twilio-ruby'
gem 'pusher'
